// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwUrsa7oPYzCYImr9bw28NJT_puR3MIgw',
    appId: '1:307093875331:web:ec0e7b85022ec9d7ecc9b6',
    messagingSenderId: '307093875331',
    projectId: 'sinum-flutter',
    authDomain: 'sinum-flutter.firebaseapp.com',
    storageBucket: 'sinum-flutter.firebasestorage.app',
    measurementId: 'G-C5PB9W4G7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBACxQeFE_kgdO4ZydN-04DTTk1JZ4-unY',
    appId: '1:307093875331:android:210d25738ab966c0ecc9b6',
    messagingSenderId: '307093875331',
    projectId: 'sinum-flutter',
    storageBucket: 'sinum-flutter.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwUrsa7oPYzCYImr9bw28NJT_puR3MIgw',
    appId: '1:307093875331:web:2507f9927b481a36ecc9b6',
    messagingSenderId: '307093875331',
    projectId: 'sinum-flutter',
    authDomain: 'sinum-flutter.firebaseapp.com',
    storageBucket: 'sinum-flutter.firebasestorage.app',
    measurementId: 'G-37D7EXSQTL',
  );
}
